package tpjavafinalhiber;
// Generated 01/12/2023 21:03:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer idequipo;
     private String nombre;
     private Integer titulares;
     private Integer suplentes;
     private String directorTecnico;
     private Integer puntos;
     private Integer partidosJugados;
     private Set partidosForIdequipo1 = new HashSet(0);
     private Set partidosForIdequipo2 = new HashSet(0);

    public Equipo() {
    }

    public Equipo(String nombre, Integer titulares, Integer suplentes, String directorTecnico, Integer puntos, Integer partidosJugados, Set partidosForIdequipo1, Set partidosForIdequipo2) {
       this.nombre = nombre;
       this.titulares = titulares;
       this.suplentes = suplentes;
       this.directorTecnico = directorTecnico;
       this.puntos = puntos;
       this.partidosJugados = partidosJugados;
       this.partidosForIdequipo1 = partidosForIdequipo1;
       this.partidosForIdequipo2 = partidosForIdequipo2;
    }
   
    public Integer getIdequipo() {
        return this.idequipo;
    }
    
    public void setIdequipo(Integer idequipo) {
        this.idequipo = idequipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getTitulares() {
        return this.titulares;
    }
    
    public void setTitulares(Integer titulares) {
        this.titulares = titulares;
    }
    public Integer getSuplentes() {
        return this.suplentes;
    }
    
    public void setSuplentes(Integer suplentes) {
        this.suplentes = suplentes;
    }
    public String getDirectorTecnico() {
        return this.directorTecnico;
    }
    
    public void setDirectorTecnico(String directorTecnico) {
        this.directorTecnico = directorTecnico;
    }
    public Integer getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }
    public Integer getPartidosJugados() {
        return this.partidosJugados;
    }
    
    public void setPartidosJugados(Integer partidosJugados) {
        this.partidosJugados = partidosJugados;
    }
    public Set getPartidosForIdequipo1() {
        return this.partidosForIdequipo1;
    }
    
    public void setPartidosForIdequipo1(Set partidosForIdequipo1) {
        this.partidosForIdequipo1 = partidosForIdequipo1;
    }
    public Set getPartidosForIdequipo2() {
        return this.partidosForIdequipo2;
    }
    
    public void setPartidosForIdequipo2(Set partidosForIdequipo2) {
        this.partidosForIdequipo2 = partidosForIdequipo2;
    }




}


