package tpjavafinalhiber;
// Generated 01/12/2023 21:03:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Partido generated by hbm2java
 */
public class Partido  implements java.io.Serializable {


     private int idpartido;
     private Equipo equipoByIdequipo1;
     private Equipo equipoByIdequipo2;
     private Date fecha;
     private Integer golesEq1;
     private Integer golesEq2;

    public Partido() {
    }

	
    public Partido(int idpartido) {
        this.idpartido = idpartido;
    }
    public Partido(int idpartido, Equipo equipoByIdequipo1, Equipo equipoByIdequipo2, Date fecha, Integer golesEq1, Integer golesEq2) {
       this.idpartido = idpartido;
       this.equipoByIdequipo1 = equipoByIdequipo1;
       this.equipoByIdequipo2 = equipoByIdequipo2;
       this.fecha = fecha;
       this.golesEq1 = golesEq1;
       this.golesEq2 = golesEq2;
    }
   
    public int getIdpartido() {
        return this.idpartido;
    }
    
    public void setIdpartido(int idpartido) {
        this.idpartido = idpartido;
    }
    public Equipo getEquipoByIdequipo1() {
        return this.equipoByIdequipo1;
    }
    
    public void setEquipoByIdequipo1(Equipo equipoByIdequipo1) {
        this.equipoByIdequipo1 = equipoByIdequipo1;
    }
    public Equipo getEquipoByIdequipo2() {
        return this.equipoByIdequipo2;
    }
    
    public void setEquipoByIdequipo2(Equipo equipoByIdequipo2) {
        this.equipoByIdequipo2 = equipoByIdequipo2;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getGolesEq1() {
        return this.golesEq1;
    }
    
    public void setGolesEq1(Integer golesEq1) {
        this.golesEq1 = golesEq1;
    }
    public Integer getGolesEq2() {
        return this.golesEq2;
    }
    
    public void setGolesEq2(Integer golesEq2) {
        this.golesEq2 = golesEq2;
    }




}


